repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v7.32.0"
    hooks:
      - id: eslint
        files: \.[jt]s$
        args: [-c, chest/.eslintrc.cjs]
        additional_dependencies:
          - "@babel/eslint-parser@7.16.0"
          - "@typescript-eslint/eslint-plugin@5.3.0"
          - "@typescript-eslint/parser@5.3.0"
          - eslint@7.32.0
          - eslint-config-prettier@8.3.0
          - eslint-config-standard@16.0.3
          - eslint-plugin-import@2.25.2
          - eslint-plugin-prettier@4.0.0
          - prettier@2.4.1
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.4.1"
    hooks:
      - id: prettier
        files: \.[jt]s$
        args: [--config, chest/.prettierrc]
